#!/bin/bash 

CASE_NAME=UNKNOWN
NOVNC_URL='http://mycuster/kanaka-noVNC-33e1462/vnc_auto.html'

CASE_SCRIPT=$(realpath ${1:-case_config.ini})
SITE_SCRIPT=$(realpath ${2:-site_config.ini})
TileSet=${3:-defaulTS}

# get case-specifig config paths (overriding defaults)
if [ -f "${CASE_SCRIPT}" ]; then
  sed -e "s@\[CASE\]@#!/bin/bash@" "${CASE_SCRIPT}" > case_config
  . case_config
fi

# get site-specifig config paths (overriding defaults)
if [ -f "${SITE_SCRIPT}" ]; then
  sed -e "s@\[SITE\]@#!/bin/bash@" "${SITE_SCRIPT}" > site_config
  . site_config
fi

NUM=$( wc -l ${FILEPATH}| sed -e "s}^\([0-9]*\).*}\1}" )

function min {
   ( [ $1 -le $2 ] && echo $1 ) || ( [ $2 -lt $1 ] && echo $2 ) 
}

DATE=$(date +%F_%H-%M-%S)

# sort student file by login
sort -o list_students -t ';' -k 3 ${FILEPATH}

# sort machine/login file by login
sort -o list_machines -t ',' -k 2 directconnection.csv

echo '{ "nodes": [' > nodes.json
#echo 'echo '' >> nodes.json' >> nodes.json
i=0
while IFS=';' read -r -u3 line || [[ -n "$line" ]] && IFS=',' read -r -u4 line2; do

  i2=$((2*(i+1)))
  i0=$(printf "%03d" $((i+1)))

  # Student values
  IFS=';' read -r -a aline <<<$line

  STUDENT=${aline[0]}
  echo "Student : " ${STUDENT} 

  MAILstudent=${aline[1]}
  echo "Student mail : " ${MAILstudent} 

  USERstudent=${aline[2]//[[:blank:]]/}
  #HOMEstudent=$HOMEstudents$USERstudent #TODO : change if home is in another place???
  #echo "Student home dir : $HOMEstudent"


  # Machine values
  IFS=',' read -r -a aline2 <<<$line2

  MACHINE=${aline2[0]}
  echo "Machine : " ${MACHINE} 
  
  if [ $i -gt 0 ]; then
      echo '},' >> nodes.json
  fi

  pass=${line##* }

  echo '{"title": "'${STUDENT}'",' >> nodes.json

  URL=$(echo $NOVNC_URL | envsubst) # expand envars in $NOVNC_URL

  IFS=';' read -r -a passline <<<$( grep ${USERstudent} list_password )

  password=${passline[1]//[[:blank:]]/}

  echo ' "url" : "'${URL}'?host='${MACHINE}'&port='${VNCPORT}'&encrypt=0&password='${passord}'&true_color=1",' >> nodes.json
  echo ' "comment" : "'${MAILstudent}' '${USERstudent}' '${DATE}'",' >> nodes.json
  echo ' "tags"  : ["'$TileSet'"],' >> nodes.json
  echo '  "variable" : "ID-'$i0'",' >> nodes.json

  i=$(( i + 1 ))
done 3< list_students 4< list_machines

echo '}' >> nodes.json
echo '] }' >> nodes.json

echo "var text_ = " > nodes.js
cat nodes.json >> nodes.js
echo 'var jsDataTab = text_.nodes;' >> nodes.js

#../../build_qr

exit 0
