#!/bin/bash

DEBUG=$1
if [ X"$DEBUG" != X ]; then
    set -vx
fi

VNCDIR=${HOME}/.vnc

if [ -f $VNCDIR/site_config ]; then
    . $VNCDIR/site_config
fi

# TODO : Change LOGNAME definition if needed
LOGNAME=${USER}
# TODO : Change PORTID definition with LDAP DB !
i=$(id -u)
# PORTID gives the last three numbers of the PORT (and SOCKETdomain the thousands for each tiledsets).
PORTID=$( printf "%03d"  $((10#$i % 1000)) )


DATE=$(date +%F_%H-%M)
LOGFILE=${VNCDIR}/out_del_$(hostname)_${DATE}_$$

pgrep -fa x11vnc  |grep -v tee |tee -a $LOGFILE

pgrep -fa x11vnc |grep $LOGNAME |grep ${VNCDIR}/passvnc_
RET=$?

if [ ${RET} -eq 0 ]; then
    export PIDvnc=$( pgrep -fa x11vnc |grep $LOGNAME |grep ${VNCDIR}/passvnc_ |sed -e 's/\([0-9]*\) .*/\1/' )
    echo "VNC processes : " ${PIDvnc[@]} ". Number " ${#PIDvnc[@]} >> $LOGFILE
    if [ X"${PIDvnc[@]}" != X ]; then
	kill -9 ${PIDvnc[@]} |tee -a $LOGFILE
	zenity --info --text "VNC closed." &
    fi

    pgrep -fa x11vnc |grep -v tee |tee -a $LOGFILE
    pgrep -fa ssh |grep $LOGNAME | grep ${HTTP_FRONTEND} |sed -e 's/\([0-9]*\) .*/\1/' |tee -a $LOGFILE
    
    export PIDssh=$( pgrep -fa ssh |grep $LOGNAME | grep ${HTTP_FRONTEND} |sed -e 's/\([0-9]*\) .*/\1/' )
    echo "All PID ssh to be killed : |${PIDssh[@]}|"  |tee -a $LOGFILE
    if [ X"${PIDssh[@]}" != X ]; then
	kill ${PIDssh[@]} |tee -a $LOGFILE
    fi
fi
