#!/bin/bash

CASE_NAME=UNKNOWN
NOVNC_URL='http://mycuster/kanaka-noVNC-33e1462/vnc_auto.html'

CASE_SCRIPT=$(realpath ${1:-case_config.ini})
SITE_SCRIPT=$(realpath ${2:-site_config.ini})
TileSet=${3:-defaulTS}

# get case-specifig config paths (overriding defaults)
if [ -f "${CASE_SCRIPT}" ]; then
  sed -e "s@\[CASE\]@#!/bin/bash@" "${CASE_SCRIPT}" > case_config
  . case_config
fi

# get site-specifig config paths (overriding defaults)
if [ -f "${SITE_SCRIPT}" ]; then
  sed -e "s@\[SITE\]@#!/bin/bash@" "${SITE_SCRIPT}" > site_config
  . site_config
fi

IFS=';' read -a DATA <<< $(cat ${CONFIGPATH} | sed 's/ *; */;/g')
FILEPATH=${DATA[0]}
IdClassroom=${DATA[1]}

NUM=$( wc -l ${FILEPATH}| sed -e "s}^\([0-9]*\).*}\1}" )

function min {
   ( [ $1 -le $2 ] && echo $1 ) || ( [ $2 -lt $1 ] && echo $2 ) 
}

DATE=$(date +%F_%H-%M-%S)

echo '{ "nodes": [' > nodes.json
#echo 'echo '' >> nodes.json' >> nodes.json
i=0
while IFS=';' read -r -u3 line && IFS='' read -r -u4 line2 || [[ -n "$line" ]]; do

  i2=$((2*(i+1)))
  i0=$(printf "%03d" $((i+1)))
  thishost=${line2% *}
  pass=${line2##* }

  # Student values
  IFS=';' read -r -a aline <<<$line

  STUDENT=${aline[0]}
  echo "Student : " ${STUDENT} 

  MAILstudent=${aline[1]}
  echo "Student mail : " ${MAILstudent} 

  USERstudent=${aline[2]//[[:blank:]]/}
  
  if [ $i -gt 0 ]; then
      echo '},' >> nodes.json
  fi

  echo '{"title" : "'${STUDENT}'",' >> nodes.json

  URL=$(echo $NOVNC_URL | envsubst) # expand envars in $NOVNC_URL
  echo ' "url" : "'${URL}'?host='${HTTP_FRONTEND}'&port='${SOCKETdomain}${i0}'&encrypt=0&password='${pass}'&true_color=1",' >> nodes.json

  echo ' "usersNotes"  : "node '$i'  : host '${thishost}' User mail '${MAILstudent}'",' >> nodes.json

  echo ' "tags"  : ["'$TileSet'"],' >> nodes.json
  echo '  "variable" : "ID-'$i0'",' >> nodes.json

  echo '"connection" : 1' >> nodes.json
  
  i=$(( i + 1 ))
done 3< ${FILEPATH} 4< list_dockers_pass

echo '}' >> nodes.json
echo '] }' >> nodes.json

echo "var text_ = " > nodes.js
cat nodes.json >> nodes.js
echo 'var jsDataTab = text_.nodes;' >> nodes.js

#../../build_qr

exit 0
